In [1]:
# Initialize Otter
import otter
grader = otter.Notebook("hw02.ipynb")

# Homework 2: Arrays and Tables

Please complete this notebook by filling in the cells provided. Before you begin, execute the following cell to load the provided tests.

In [2]:
# Don't change this cell; just run it. 
# When you log-in please hit return (not shift + return) after typing in your email
import numpy as np
from datascience import *
import warnings
warnings.simplefilter('ignore', FutureWarning)

**Helpful Resource:**
- [Python Reference](http://data8.org/sp21/python-reference.html): Cheat sheet of helpful array & table methods used in Data 8!

**Recommended Reading:**
- [What is Data Science](http://www.inferentialthinking.com/chapters/01/what-is-data-science.html)
- [Causality and Experiments](http://www.inferentialthinking.com/chapters/02/causality-and-experiments.html) 
- [Programming in Python](http://www.inferentialthinking.com/chapters/03/programming-in-python.html)

For all problems that you must write explanations and sentences for, you **must** provide your answer in the designated space. Moreover, throughout this homework and all future ones, please be sure to not re-assign variables throughout the notebook! For example, if you use `max_temperature` in your answer to one question, do not reassign it later on. Otherwise, you will fail tests that you thought you were passing previously!

**Deadline:**

This assignment is due Tuesday, June 29 at 11:59 P.M PST. Late work will not be accepted as per the [policies](http://data8.org/su21/policies.html) page.

### **Note: This homework has hidden tests on it. That means even though tests may say 100% passed, doesn't mean your final grade will be 100%. We will be running more tests for correctness once everyone turns in the homework.**

Directly sharing answers is not okay, but discussing problems with the course staff or with other students is encouraged. Refer to the policies page to learn more about how to learn cooperatively.

You should start early so that you have time to get help if you're stuck. Office hours are held Monday-Friday. The schedule appears on the [course website](http://data8.org/su21/office-hours.html).


## Creating Arrays

In [3]:
# Run this cell to set up the notebook, but please don't change it.

import numpy as np
from datascience import *

**Question 1.** Make an array called `weird_numbers` containing the following numbers (in the given order) **(2 Points)**:

1. -2
2. the sine of 12
3. 3
4. 5 to the power of the cosine of 12

*Hint:* `sin` and `cos` are functions in the `math` module. Importing modules is covered in 2.1 of Lab 2!

*Note:* Python lists are different/behave differently than numpy arrays. In Data 8, we use numpy arrays, so please make an **array**, not a python list.

<!--
BEGIN QUESTION
name: q1_1
points:
 - 0
 - 2
-->

In [5]:
# Our solution involved one extra line of code before creating
# weird_numbers.
from math import sin,cos
weird_numbers = make_array(-2,sin(12),3,5**cos(12))
weird_numbers

array([-2.        , -0.53657292,  3.        ,  3.88891638])

In [6]:
grader.check("q1_1")

q1_1 results: All test cases passed!

**Question 2.** Make an array called `book_title_words` containing the following three strings: "Eats", "Shoots", and "and Leaves". **(2 Points)**

<!--
BEGIN QUESTION
name: q1_2
points:
 - 0
 - 0
 - 0
 - 0
 - 2
-->

In [7]:
book_title_words = make_array( "Eats", "Shoots", "and Leaves")
book_title_words

array(['Eats', 'Shoots', 'and Leaves'], dtype='<U10')

In [8]:
grader.check("q1_2")

q1_2 results: All test cases passed!

Strings have a method called `join`.  `join` takes one argument, an array of strings.  It returns a single string.  Specifically, the value of `a_string.join(an_array)` is a single string that's the [concatenation](https://en.wikipedia.org/wiki/Concatenation) ("putting together") of all the strings in `an_array`, **except** `a_string` is inserted in between each string.

**Question 3.** Use the array `book_title_words` and the method `join` to make two strings **(5 Points)**:

1. "Eats, Shoots, and Leaves" (call this one `with_commas`)
2. "Eats Shoots and Leaves" (call this one `without_commas`)

*Hint:* If you're not sure what `join` does, first try just calling, for example, `"foo".join(book_title_words)` .

<!--
BEGIN QUESTION
name: q1_3
points:
 - 2.5
 - 2.5
-->

In [13]:
with_commas =", ".join(book_title_words)
without_commas = " ".join(book_title_words)

# These lines are provided just to print out your answers.
print('with_commas:', with_commas)
print('without_commas:', without_commas)

with_commas: Eats, Shoots, and Leaves
without_commas: Eats Shoots and Leaves


In [14]:
grader.check("q1_3")

q1_3 results: All test cases passed!

## Indexing Arrays

In [15]:
# Run this cell to set up the notebook, but please don't change it.

import numpy as np
from datascience import *

These exercises give you practice accessing individual elements of arrays.  In Python (and in many programming languages), elements are accessed by *index*, so the first element is the element at index 0. Indices must be **integers**.

***Note:* If you have previous coding experience, you may be familiar with bracket notation. DO NOT use bracket notation when indexing (i.e. `arr[0]`), as this can yield different data type outputs than what we will be expecting. This can cause you to fail an autograder test.**

Be sure to refer to the [Python Reference](http://data8.org/su21/python-reference.html) on the website if you feel stuck!

**Question 1.** The cell below creates an array of some numbers.  Set `third_element` to the third element of `some_numbers`. **(2 Points)**

<!--
BEGIN QUESTION
name: q2_1
points:
 - 0
 - 2
-->

In [16]:
some_numbers = make_array(-1, -3, -6, -10, -15)

third_element = some_numbers.item(2)
third_element

-6

In [17]:
grader.check("q2_1")

q2_1 results: All test cases passed!

**Question 2.** The next cell creates a table that displays some information about the elements of `some_numbers` and their order.  Run the cell to see the partially-completed table, then fill in the missing information (the cells that say "Ellipsis") by assigning `blank_a`, `blank_b`, `blank_c`, and `blank_d` to the correct elements in the table. **(6 Points)**

Hint: Replace the … with strings or numbers. As a reminder, indices should be **integers**.

<!--
BEGIN QUESTION
name: q2_2
points:
 - 1.5
 - 1.5
 - 1.5
 - 1.5
-->

In [19]:
blank_a = "third"
blank_b = "fourth"
blank_c = 0
blank_d = 3
elements_of_some_numbers = Table().with_columns(
    "English name for position", make_array("first", "second", blank_a, blank_b, "fifth"),
    "Index",                     make_array(blank_c, 1, 2, blank_d, 4),
    "Element",                   some_numbers)
elements_of_some_numbers

English name for position | Index | Element
first                     | 0     | -1
second                    | 1     | -3
third                     | 2     | -6
fourth                    | 3     | -10
fifth                     | 4     | -15

In [20]:
grader.check("q2_2")

q2_2 results: All test cases passed!

**Question 3.** You'll sometimes want to find the **last** element of an array.  Suppose an array has 142 elements.  What is the index of its last element? **(2 Points)**

<!--
BEGIN QUESTION
name: q2_3
points:
 - 2
-->

In [21]:
index_of_last_element = 141

In [22]:
grader.check("q2_3")

q2_3 results: All test cases passed!

More often, you don't know the number of elements in an array, its *length*.  (For example, it might be a large dataset you found on the Internet.)  The function `len` takes a single argument, an array, and returns the `len`gth of that array (an integer).

**Question 4.** The cell below loads an array called `president_birth_years`.  Calling `.column(...)` on a table returns an array of the column specified, in this case the `Birth Year` column of the `president_births` table. The last element in that array is the most recent birth year of any deceased president. Assign that year to `most_recent_birth_year`. **(5 Points)**

<!--
BEGIN QUESTION
name: q2_4
points:
 - 5
-->

In [25]:
president_birth_years = Table.read_table("president_births.csv").column('Birth Year')

most_recent_birth_year = president_birth_years.item(len(president_birth_years)-1)
most_recent_birth_year

1917

In [26]:
grader.check("q2_4")

q2_4 results: All test cases passed!

**Question 5.** Finally, assign `sum_of_birth_years` to the sum of the first, sixteenth, and last birth year in `president_birth_years`. **(6 Points)**

<!--
BEGIN QUESTION
name: q2_5
points:
 - 0
 - 6
-->

In [28]:
sum_of_birth_years = president_birth_years.item(0)+ president_birth_years.item(15) + most_recent_birth_year
sum_of_birth_years

5457

In [29]:
grader.check("q2_5")

q2_5 results: All test cases passed!

## Basic Array Arithmetic

In [30]:
# Run this cell to set up the notebook, but please don't change it.

import numpy as np
from datascience import *

**Question 1.** Multiply the numbers 42, -4224, 424224242, and 250 by 157. Assign each variable below such that `first_product` is assigned to the result of $42 * 157$, `second_product` is assigned to the result of $-4224 * 157$, and so on. **(2 Points)**

For this question, **don't** use arrays.

<!--
BEGIN QUESTION
name: q3_1
points:
 - 0
 - 2
-->

In [31]:
first_product = 42 * 157
second_product = -4224 * 157
third_product = 424224242 * 157
fourth_product = 250 * 157
print(first_product, second_product, third_product, fourth_product)

6594 -663168 66603205994 39250


In [32]:
grader.check("q3_1")

q3_1 results: All test cases passed!

**Question 2.** Now, do the same calculation, but using an array called `numbers` and only a single multiplication (`*`) operator.  Store the 4 results in an array named `products`. **(2 Points)**

<!--
BEGIN QUESTION
name: q3_2
points:
 - 0
 - 2
-->

In [34]:
numbers = make_array(42,-4224,424224242,250)
products = numbers * 157
products

array([       6594,     -663168, 66603205994,       39250])

In [35]:
grader.check("q3_2")

q3_2 results: All test cases passed!

**Question 3.** Oops, we made a typo!  Instead of 157, we wanted to multiply each number by 1577.  Compute the correct products in the cell below using array arithmetic.  Notice that your job is really easy if you previously defined an array containing the 4 numbers. **(2 Points)**

<!--
BEGIN QUESTION
name: q3_3
points:
 - 0
 - 2
-->

In [36]:
correct_products = numbers * 1577
correct_products

array([       66234,     -6661248, 669001629634,       394250])

In [37]:
grader.check("q3_3")

q3_3 results: All test cases passed!

**Question 4.** We've loaded an array of temperatures in the next cell.  Each number is the highest temperature observed on a day at a climate observation station, mostly from the US.  Since they're from the US government agency [NOAA](noaa.gov), all the temperatures are in Fahrenheit.  Convert them all to Celsius by first subtracting 32 from them, then multiplying the results by $\frac{5}{9}$. Make sure to **ROUND** the final result after converting to Celsius to the nearest integer using the `np.round` function. **(5 Points)**

<!--
BEGIN QUESTION
name: q3_4
points:
 - 1
 - 1
 - 1
 - 2
-->

In [38]:
max_temperatures = Table.read_table("temperatures.csv").column("Daily Max Temperature")

celsius_max_temperatures = np.round((max_temperatures -32)*5/9)
celsius_max_temperatures

array([-4., 31., 32., ..., 17., 23., 16.])

In [39]:
grader.check("q3_4")

q3_4 results: All test cases passed!

**Question 5.** The cell below loads all the *lowest* temperatures from each day (in Fahrenheit).  Compute the size of the daily temperature range for each day.  That is, compute the difference between each daily maximum temperature and the corresponding daily minimum temperature.  **Pay attention to the units, give your answer in Celsius!** Make sure **NOT** to round your answer for this question! Note: Remember that in Question 4, `celsius_max_temperatures` was rounded, so you might not want to use that in this question. **(5 Points)**


<!--
BEGIN QUESTION
name: q3_5
points:
 - 0
 - 5
 - 0
-->

In [42]:
min_temperatures = Table.read_table("temperatures.csv").column("Daily Min Temperature")

celsius_temperature_ranges = (max_temperatures-32)*5/9-(min_temperatures-32)*5/9
celsius_temperature_ranges

array([ 6.66666667, 10.        , 12.22222222, ..., 17.22222222,
       11.66666667, 11.11111111])

In [43]:
grader.check("q3_5")

q3_5 results: All test cases passed!

## World Population

In [44]:
# Run this cell to set up the notebook, but please don't change it.

import numpy as np
from datascience import *

Remember that the tests from this point on will **not** necessarily tell you whether or not your answers are correct.

The cell below loads a table of estimates of the world population for different years, starting in 1950. The estimates come from the [US Census Bureau website](https://www.census.gov/en.html).

In [45]:
world = Table.read_table("world_population.csv").select('Year', 'Population')
world.show(4)

The name `population` is assigned to an array of population estimates.

In [46]:
population = world.column(1)
population

array([2557628654, 2594939877, 2636772306, 2682053389, 2730228104,
       2782098943, 2835299673, 2891349717, 2948137248, 3000716593,
       3043001508, 3083966929, 3140093217, 3209827882, 3281201306,
       3350425793, 3420677923, 3490333715, 3562313822, 3637159050,
       3712697742, 3790326948, 3866568653, 3942096442, 4016608813,
       4089083233, 4160185010, 4232084578, 4304105753, 4379013942,
       4451362735, 4534410125, 4614566561, 4695736743, 4774569391,
       4856462699, 4940571232, 5027200492, 5114557167, 5201440110,
       5288955934, 5371585922, 5456136278, 5538268316, 5618682132,
       5699202985, 5779440593, 5857972543, 5935213248, 6012074922,
       6088571383, 6165219247, 6242016348, 6318590956, 6395699509,
       6473044732, 6551263534, 6629913759, 6709049780, 6788214394,
       6866332358, 6944055583, 7022349283, 7101027895, 7178722893,
       7256490011])

In this question, you will apply some built-in Numpy functions to this array. Numpy is a module that is often used in Data Science!

<img src="array_diff.png" style="width: 600px;"/>

The difference function `np.diff` subtracts each element in an array from the element after it within the array. As a result, the length of the array `np.diff` returns will always be one less than the length of the input array.

<img src="array_cumsum.png" style="width: 700px;"/>

The cumulative sum function `np.cumsum` outputs an array of partial sums. For example, the third element in the output array corresponds to the sum of the first, second, and third elements.

**Note:** This homework aims to get you comfortable with array arithmetic using methods like `np.diff` and `np.cumsum`, but they are not heavily used later in the course.

**Question 1.** Very often in data science, we are interested in understanding how values change with time. Use `np.diff` and `np.max` (or just `max`) to calculate the largest annual change in population between any two consecutive years. **(4 Points)**

<!--
BEGIN QUESTION
name: q4_1
points:
 - 4
-->

In [47]:
largest_population_change = max(np.diff(population))
largest_population_change

87515824

In [48]:
grader.check("q4_1")

q4_1 results: All test cases passed!

**Question 2.** What do the values in the resulting array represent (choose one)? **(5 Points)**

*Tip: Look at the population array and compute the actual population changes for the first couple years of each option.* 

In [49]:
np.cumsum(np.diff(population))

array([  37311223,   79143652,  124424735,  172599450,  224470289,
        277671019,  333721063,  390508594,  443087939,  485372854,
        526338275,  582464563,  652199228,  723572652,  792797139,
        863049269,  932705061, 1004685168, 1079530396, 1155069088,
       1232698294, 1308939999, 1384467788, 1458980159, 1531454579,
       1602556356, 1674455924, 1746477099, 1821385288, 1893734081,
       1976781471, 2056937907, 2138108089, 2216940737, 2298834045,
       2382942578, 2469571838, 2556928513, 2643811456, 2731327280,
       2813957268, 2898507624, 2980639662, 3061053478, 3141574331,
       3221811939, 3300343889, 3377584594, 3454446268, 3530942729,
       3607590593, 3684387694, 3760962302, 3838070855, 3915416078,
       3993634880, 4072285105, 4151421126, 4230585740, 4308703704,
       4386426929, 4464720629, 4543399241, 4621094239, 4698861357])

1) The total population change between consecutive years, starting at 1951.

2) The total population change between 1950 and each later year, starting at 1951.

3) The total population change between 1950 and each later year, starting inclusively at 1950.

<!--
BEGIN QUESTION
name: q4_2
points:
 - 0
 - 0
 - 5
-->

In [50]:
# Assign cumulative_sum_answer to 1, 2, or 3
cumulative_sum_answer = 2

In [51]:
grader.check("q4_2")

q4_2 results: All test cases passed!

## Old Faithful

In [52]:
# Run this cell to set up the notebook, but please don't change it.

import numpy as np
from datascience import *

Old Faithful is a geyser in Yellowstone that erupts every 44 to 125 minutes (according to [Wikipedia](https://en.wikipedia.org/wiki/Old_Faithful)). People are [often told that the geyser erupts every hour](http://yellowstone.net/geysers/old-faithful/), but in fact the waiting time between eruptions is more variable. Let's take a look.

**Question 1.** The first line below assigns `waiting_times` to an array of 272 consecutive waiting times between eruptions, taken from a classic 1938 dataset. Assign the names `shortest`, `longest`, and `average` so that the `print` statement is correct. **(2 Points)**

<!--
BEGIN QUESTION
name: q5_1
points:
 - 0
 - 0
 - 1
 - 1
-->

In [55]:
waiting_times = Table.read_table('old_faithful.csv').column('waiting')

shortest = min(waiting_times)
longest = max(waiting_times)
average = np.average(waiting_times)

print("Old Faithful erupts every", shortest, "to", longest, "minutes and every", average, "minutes on average.")

Old Faithful erupts every 43 to 96 minutes and every 70.8970588235294 minutes on average.


In [56]:
grader.check("q5_1")

q5_1 results: All test cases passed!

**Question 2.** Assign `biggest_decrease` to the biggest decrease in waiting time between two consecutive eruptions. For example, the third eruption occurred after 74 minutes and the fourth after 62 minutes, so the decrease in waiting time was 74 - 62 = 12 minutes. **(4 Points)**

*Hint 1*: You'll need an array arithmetic function [mentioned in the textbook](https://inferentialthinking.com/chapters/05/1/Arrays.html#functions-on-arrays). You have also seen this function earlier in the homework!

*Hint 2*: We want to return the absolute value of the biggest decrease.

<!--
BEGIN QUESTION
name: q5_2
points:
 - 0
 - 0
 - 4
-->

In [61]:
biggest_decrease = abs(min(np.diff(waiting_times)))
biggest_decrease

45

In [62]:
grader.check("q5_2")

q5_2 results: All test cases passed!

**Question 3.** If you expected Old Faithful to erupt every hour, you would expect to wait a total of `60 * k` minutes to see `k` eruptions. Set `difference_from_expected` to an array with 272 elements, where the element at index `i` is the absolute difference between the actual and expected total amount of waiting time to see the first `i+1` eruptions. **(8 Points)**

*Hint*: You'll need to compare a cumulative sum to a range. You'll go through `np.arange` more thoroughly in Lab 3, but you can read about it in this [textbook section](https://www.inferentialthinking.com/chapters/05/2/Ranges.html).

For example, since the first three waiting times are 79, 54, and 74, the total waiting time for 3 eruptions is 79 + 54 + 74 = 207. The expected waiting time for 3 eruptions is 60 * 3 = 180. Therefore, `difference_from_expected.item(2)` should be $|207 - 180| = 27$.

<!--
BEGIN QUESTION
name: q5_3
points:
 - 1
 - 7
-->

In [71]:
difference_from_expected = abs(np.cumsum(waiting_times)-np.arange(60,60*273,60))
difference_from_expected

array([  19,   13,   27,   29,   54,   49,   77,  102,   93,  118,  112,
        136,  154,  141,  164,  156,  158,  182,  174,  193,  184,  171,
        189,  198,  212,  235,  230,  246,  264,  283,  296,  313,  319,
        339,  353,  345,  333,  353,  352,  382,  402,  400,  424,  422,
        435,  458,  462,  455,  477,  476,  491,  521,  515,  535,  529,
        552,  563,  567,  584,  605,  604,  628,  616,  638,  638,  670,
        688,  706,  711,  724,  746,  742,  761,  772,  774,  790,  790,
        808,  824,  847,  862,  884,  894,  899,  912,  940,  956,  976,
        964,  990,  990, 1020, 1010, 1028, 1031, 1043, 1067, 1082, 1073,
       1095, 1097, 1125, 1114, 1137, 1158, 1145, 1169, 1161, 1187, 1208,
       1223, 1222, 1251, 1270, 1269, 1290, 1280, 1305, 1304, 1331, 1324,
       1333, 1350, 1346, 1374, 1395, 1380, 1402, 1397, 1427, 1412, 1435,
       1431, 1460, 1446, 1468, 1459, 1485, 1478, 1497, 1518, 1518, 1540,
       1557, 1573, 1572, 1592, 1581, 1617, 1610, 16

In [72]:
grader.check("q5_3")

q5_3 results: All test cases passed!

**Question 4.** Let’s imagine your guess for the next waiting time was always just the length of the previous waiting time. If you always guessed the previous waiting time, how big would your error in guessing the waiting times be, on average? **(8 Points)**

For example, since the first three waiting times are 79, 54, and 74, the average difference between your guess and the actual time for just the second and third eruption would be $\frac{|79-54|+ |54-74|}{2} = 22.5$.

<!--
BEGIN QUESTION
name: q5_4
points:
 - 0
 - 8
-->

In [79]:
average_error = np.average((abs(np.diff(waiting_times))))
average_error

20.52029520295203

In [80]:
grader.check("q5_4")

q5_4 results: All test cases passed!

## Tables

In [81]:
# Run this cell to set up the notebook, but please don't change it.

import numpy as np
from datascience import *

**Question 1.** Suppose you have 4 apples, 3 oranges, and 3 pineapples.  (Perhaps you're using Python to solve a high school Algebra problem.)  Create a table that contains this information.  It should have two columns: `fruit name` and `count`.  Assign the new table to the variable `fruits`. **(2 Points)**

**Note:** Use lower-case and singular words for the name of each fruit, like `"apple"`.

<!--
BEGIN QUESTION
name: q6_1
points:
 - 2
-->

In [84]:
# Our solution uses 1 statement split over 3 lines.
fruits = Table().with_columns(
        "fruit name",make_array("apple","orange","pineapple"),
        "count",make_array(4,3,3))
fruits

fruit name | count
apple      | 4
orange     | 3
pineapple  | 3

In [85]:
grader.check("q6_1")

q6_1 results: All test cases passed!

**Question 2.** The file `inventory.csv` contains information about the inventory at a fruit stand.  Each row represents the contents of one box of fruit. Load it as a table named `inventory` using the `Table.read_table()` function. `Table.read_table(...)` takes one argument (data file name in string format) and returns a table. **(2 Points)**

<!--
BEGIN QUESTION
name: q6_2
points:
 - 2
-->

In [86]:
inventory = Table.read_table("inventory.csv")
inventory

box ID | fruit name | count
53686  | kiwi       | 45
57181  | strawberry | 123
25274  | apple      | 20
48800  | orange     | 35
26187  | strawberry | 255
57930  | grape      | 517
52357  | strawberry | 102
43566  | peach      | 40

In [87]:
grader.check("q6_2")

q6_2 results: All test cases passed!

**Question 3.** Does each box at the fruit stand contain a different fruit? Set `all_different` to `True` if each box contains a different fruit or to `False` if multiple boxes contain the same fruit. **(2 Points)**

*Hint:* You don't have to write code to calculate the True/False value for `all_different`. Just look at the `inventory` table and assign `all_different` to either `True` or `False` according to what you can see from the table in answering the question.

<!--
BEGIN QUESTION
name: q6_3
points:
 - 0
 - 2
-->

In [88]:
all_different = False
all_different

False

In [89]:
grader.check("q6_3")

q6_3 results: All test cases passed!

**Question 4.** The file `sales.csv` contains the number of fruit sold from each box last Saturday.  It has an extra column called "price per fruit (\$)" that's the price *per item of fruit* for fruit in that box.  The rows are in the same order as the `inventory` table.  Load these data into a table called `sales`. **(2 Points)**

<!--
BEGIN QUESTION
name: q6_4
points:
 - 2
-->

In [90]:
sales = Table.read_table("sales.csv")
sales

box ID | fruit name | count sold | price per fruit ($)
53686  | kiwi       | 3          | 0.5
57181  | strawberry | 101        | 0.2
25274  | apple      | 0          | 0.8
48800  | orange     | 35         | 0.6
26187  | strawberry | 25         | 0.15
57930  | grape      | 355        | 0.06
52357  | strawberry | 102        | 0.25
43566  | peach      | 17         | 0.8

In [91]:
grader.check("q6_4")

q6_4 results: All test cases passed!

**Question 5.** How many fruits did the store sell in total on that day? **(4 Points)**

<!--
BEGIN QUESTION
name: q6_5
points:
 - 0
 - 4
-->

In [92]:
total_fruits_sold = sum(sales.column("count sold"))
total_fruits_sold

638

In [93]:
grader.check("q6_5")

q6_5 results: All test cases passed!

**Question 6.** What was the store's total revenue (the total price of all fruits sold) on that day? **(5 Points)**

*Hint:* If you're stuck, think first about how you would compute the total revenue from just the grape sales.

<!--
BEGIN QUESTION
name: q6_6
points:
 - 0
 - 5
-->

In [97]:
total_revenue = sum(sales.column("count sold")*sales.column("price per fruit ($)"))
total_revenue

106.85

In [98]:
grader.check("q6_6")

q6_6 results: All test cases passed!

**Question 7.** Make a new table called `remaining_inventory`.  It should have the same rows and columns as `inventory`, except that the amount of fruit sold from each box should be subtracted from that box's **original** count, so that the "count" is **updated to be** the amount of fruit remaining after Saturday. **(6 Points)**

<!--
BEGIN QUESTION
name: q6_7
points:
 - 0
 - 3
 - 3
-->

In [99]:
remaining_inventory = inventory.drop("count").with_columns(
"count",inventory.column("count")-sales.column("count sold")
)
remaining_inventory

box ID | fruit name | count
53686  | kiwi       | 42
57181  | strawberry | 22
25274  | apple      | 20
48800  | orange     | 0
26187  | strawberry | 230
57930  | grape      | 162
52357  | strawberry | 0
43566  | peach      | 23

In [100]:
grader.check("q6_7")

q6_7 results: All test cases passed!

---

To double-check your work, the cell below will rerun all of the autograder tests.

In [101]:
grader.check_all()

q1_1 results: All test cases passed!

q1_2 results: All test cases passed!

q1_3 results: All test cases passed!

q2_1 results: All test cases passed!

q2_2 results: All test cases passed!

q2_3 results: All test cases passed!

q2_4 results: All test cases passed!

q2_5 results: All test cases passed!

q3_1 results: All test cases passed!

q3_2 results: All test cases passed!

q3_3 results: All test cases passed!

q3_4 results: All test cases passed!

q3_5 results: All test cases passed!

q4_1 results: All test cases passed!

q4_2 results: All test cases passed!

q5_1 results: All test cases passed!

q5_2 results: All test cases passed!

q5_3 results: All test cases passed!

q5_4 results: All test cases passed!

q6_1 results: All test cases passed!

q6_2 results: All test cases passed!

q6_3 results: All test cases passed!

q6_4 results: All test cases passed!

q6_5 results: All test cases passed!

q6_6 results: All test cases passed!

q6_7 results: All test cases passed!

## Submission

Make sure you have run all cells in your notebook in order before running the cell below, so that all images/graphs appear in the output. The cell below will generate a zip file for you to submit. **Please save before exporting!**

In [ ]:
# Save your notebook first, then run this cell to export your submission.
grader.export(pdf=False)